### ISSUE TITLE
Rate limit from GitHub API on too many starts

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/talk-desktop#124]
```js
{
  message: "API rate limit exceeded for 109.250.170.94. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  documentation_url: 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'
}
```

**Comment by ShGKme** [comment]
From the GitHub docs:

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour

> Unauthenticated requests are associated with the originating IP address, and not the person making requests.

Proposals:
1. Disable new release checking on development (it seems mostly only developers have so many starts)
2. Make the time more "random" (1-4h). (So that a full office starting a working day at the same hour won't make requests on the same hour)
3. If there is a new version - save it and don't check again before a restart (the new version likely won't disappear).

Note: this error appears in the console but doesn't crash the app. In 2 hours the app will try again.

**Comment by nickvergessen** [comment]
> Disable new release checking on development (it seems mostly only developers have so many starts)

yeah lets do that

> Make the time more "random" (1-4h). (So that a full office starting a working day at the same hour won't make requests on the same hour)

Should have different IPs so would be okay.

> If there is a new version - save it and don't check again before a restart (the new version likely won't disappear).

Also a good idea

**Comment by ShGKme** [comment]
> Should have different IPs so would be okay.

Won't it be one "WiFi router" IP or NAT?

**Comment by nickvergessen** [comment]
Yeah, totally fine for now to ignore the issue.

Let's ignore it for now, and fix 3 in the closer future and for 2 we need another plan.
